// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MLModelSelectionMCMC
RcppExport SEXP MLModelSelectionMCMC(SEXP i_Num_of_iterations, SEXP list_Data, SEXP list_InitialValues, SEXP list_HyperPara, SEXP list_UpdatePara, SEXP list_TuningPara);
RcppExport SEXP _BayesMGLM_MLModelSelectionMCMC(SEXP i_Num_of_iterationsSEXP, SEXP list_DataSEXP, SEXP list_InitialValuesSEXP, SEXP list_HyperParaSEXP, SEXP list_UpdateParaSEXP, SEXP list_TuningParaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type i_Num_of_iterations(i_Num_of_iterationsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_Data(list_DataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_InitialValues(list_InitialValuesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_HyperPara(list_HyperParaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_UpdatePara(list_UpdateParaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_TuningPara(list_TuningParaSEXP);
    rcpp_result_gen = Rcpp::wrap(MLModelSelectionMCMC(i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara));
    return rcpp_result_gen;
END_RCPP
}
// MultiLinearModelMCMC
RcppExport SEXP MultiLinearModelMCMC(SEXP i_Num_of_iterations, SEXP list_Data, SEXP list_InitialValues, SEXP list_HyperPara, SEXP list_UpdatePara, SEXP list_TuningPara);
RcppExport SEXP _BayesMGLM_MultiLinearModelMCMC(SEXP i_Num_of_iterationsSEXP, SEXP list_DataSEXP, SEXP list_InitialValuesSEXP, SEXP list_HyperParaSEXP, SEXP list_UpdateParaSEXP, SEXP list_TuningParaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type i_Num_of_iterations(i_Num_of_iterationsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_Data(list_DataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_InitialValues(list_InitialValuesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_HyperPara(list_HyperParaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_UpdatePara(list_UpdateParaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type list_TuningPara(list_TuningParaSEXP);
    rcpp_result_gen = Rcpp::wrap(MultiLinearModelMCMC(i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesMGLM_MLModelSelectionMCMC", (DL_FUNC) &_BayesMGLM_MLModelSelectionMCMC, 6},
    {"_BayesMGLM_MultiLinearModelMCMC", (DL_FUNC) &_BayesMGLM_MultiLinearModelMCMC, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesMGLM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
