# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MLModelSelectionMCMC <- function(i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara) {
    .Call(`_BayesMGLM_MLModelSelectionMCMC`, i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara)
}

MultiLinearModelMCMC <- function(i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara) {
    .Call(`_BayesMGLM_MultiLinearModelMCMC`, i_Num_of_iterations, list_Data, list_InitialValues, list_HyperPara, list_UpdatePara, list_TuningPara)
}

